server:
  port: 8080
spring:
  application:
    name: gestion_partes
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_partes
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: admin123
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true